# Generated by Django 2.0.5 on 2021-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='namaste.jpg', upload_to='Profilepics/'),
        ),
    ]
